### PR TITLE
Documented how to define custom module formats for the TypeScript compiler so that you can import images and other files

### PR DESCRIPTION
**Pull request by joshtynjala**

### CODE REVIEW

**Comment by DorianGrey** [comment]
Are you sure this kind of module definition is sufficient? I've always had to do something like this (example for SVG)
```typescript
declare module "*.svg" {
  let __svg__: string;
  export default __svg__;
}
```
to be able to use the imported value in my code, e.g.:
```javascript
import logo from "../../../importedAssets/logo.svg";

export default () => (
  <div>
    <img src={logo} className="App-logo" alt="logo" />
  </div>
);
```
Though that might depend on the particular compiler options, esp. regarding `noImplicitAny`.

**Comment by joshtynjala** [comment]
@DorianGrey My *tsconfig.json* has `noImplicitAny` set to `true`, and this was indeed enough for me to import a PNG file without errors.

**Comment by DorianGrey** [comment]
Ok, I've cross-checked this - works fine. I'll see if I can figure out why the more complicated version was required some time ago, but the simplified declaration as provided here works fine in recent scenarios.

**Comment by wmonk** [comment]
Released in 2.13.0

**Pull request merged**
