### PR TITLE
Added mapCoverage back to createJestconfig.js

### PR DESCRIPTION
**Pull request by hellothisisjon**
Added mapCoverage back to createJestconfig.js so that coverage reports use sourcemaps for accurate coverage

### CODE REVIEW

**Comment by hellothisisjon** [comment]
This had changed in: `2.11.0 Upgrade to react-scripts@1.0.17`
without the mapCoverage option in the config I got some very odd coverage results. Even when testing the default template App.tsx it shows incorrect line coverage and line count.

**Comment by DorianGrey** [comment]
Hm... I'll have a closer look at this - the `mapCoverage` was removed since it is also absent on CRA upstream, which should also use sourcemaps due to babel transpilation.

**Comment by DorianGrey** [comment]
Ok, had a look - can confirm this problem. It seems that `mapCoverage: true` for properly dealing with the source maps provided by `typescript`. Would you mind adding a corresponding comment near that entry, so it won't get lost again on following rebases?

**Comment by hellothisisjon** [comment]
ah true, sorry didn't think of that, I'll just pass `--mapCoverage` in the `test`script in my application instead, that solves it for me since I'm not using a mix of ts and js.

**Pull request closed without merging**
