### PR TITLE
Uglifyjs update for es6 support

### PR DESCRIPTION
**Pull request by thetric**

### CODE REVIEW

**Comment by thetric** [comment]
Hm, the CI tests (Node 8, npm 5.6, test suite=simple) fails because of a missing `typescript` dependency: See https://travis-ci.org/wmonk/create-react-app-typescript/jobs/339514110#L286

**Comment by DorianGrey** [comment]
Just poked it - runs now (a previous patch added a fix for this cache-related issue).
If I got that correctly, this plugin uses `uglify-es` under the hood, which has the `ecma` config option to indicate the intended ECMAScript version. And that's the one I'm not sure about.
- The angular folks are conditionally setting this to either `5` or `6`, depending on the project's typescript configuration.
- In CRA upstream, it is always set to `8`.

I'm not sure if one of these approaches has to be taken in this case as well, or if just leaving it out and thus fall back to the default `ecma` option in the detail config.

**Comment by thetric** [comment]
I think we should specify the `ecma` option, so it doesn't depend on the default config of `uglify-es` which might change.

In the case of the concrete ECMA level I'm not quite sure but I would stick to CRA's settings. This seems to be the easiest way because we can let people use whatever TS target they want and we don't need to parse the tsconfig to set the matching `ecma` option. `uglify-es` should only minify the code, not transpile or even refactor it automatically.

**Comment by thetric** [comment]
I updated my PR to set the `ecma` level to `8` (like CRA upstream).

**Comment by DorianGrey** [comment]
Sorry for the delay - have been quite busy the last days.

Suppose it's OK to "cherry-pick" this change from upstream before the 2.0 CRA release, since it's not yet clear when it will be released.

Thanks!

**Pull request merged**
