### PR TITLE
Break fork link

### PR DESCRIPTION
**Pull request by wmonk**

### CODE REVIEW

**Comment by bootstraponline** [comment]
What's the status of this pull request?

**Comment by paulmelnikow** [comment]
I support breaking the fork link. It's frustrating not to be able to search this repo, and I bet it also gets bad SEO.

I've broken fork links a few times before. The way I've always done that is by emailing github support.

**Comment by raptoria** [comment]
+1

**Comment by nickmccurdy** [comment]
Out of curiosity, why does GitHub still display this as a fork?

image

**Comment by wmonk** [comment]
@nickmccurdy this is in the process of being removed. The PR was just for code reasons.

**Comment by wmonk** [comment]
All done

**Comment by raptoria** [comment]
what version of cra-ts will this be in?

**Pull request merged**
