### PR TITLE
Update tslint.json template

### PR DESCRIPTION
**Pull request by iamclaytonray**
Fixes: `Array has too many items. Expected {0} or fewer.` on member-ordering

### CODE REVIEW

**Comment by iamclaytonray** [comment]
<a href="https://palantir.github.io/tslint/rules/member-ordering/">Here is a reference on the docs</a>

**Comment by iamclaytonray** [comment]
^ Just kidding. That somehow broke for me. They must have outdated docs. Let me research further and figure out why I'm getting a warning

**Comment by DorianGrey** [comment]
Closing this, since the repository containing the change no longer exists.

**Comment by iamclaytonray** [comment]
Yeah, that's fine. I mean to close this a while back

**Comment by rosdi** [comment]
I am confused, so what is the correct format for "member-ordering" in tslint.json? According to [the doc](https://palantir.github.io/tslint/rules/member-ordering/) it should be in this format:

```
"member-ordering": [
    true,
    {
        "order": [
            "public-before-private",
            "static-before-instance",
            "variables-before-functions"
        ]
    }
],
```

But in the template it is still:

```
"member-ordering": [
    true,
    "public-before-private",
    "static-before-instance",
    "variables-before-functions"
],
```

Which generates `Array has too many items. Expected {0} or fewer.` warning.

**Pull request closed without merging**
