### PR TITLE
Replace TSLint with CRA's ESLint config

### LINKED ISSUE #33: Support for compilerOptions from tsconfig.json in Jest-Tests?
I am using Decorators in my app and would like to unit-test the functions that use them. You currently pass a fixed config-object into the ts-compiler that transforms the files before running them trough jest here: https://github.com/wmonk/create-react-app-typescript/blob/master/packages/react-scripts/config/jest/typescriptTransform.js#L10

```js
// Copyright 2004-present Facebook. All Rights Reserved.

const tsc = require('typescript');

module.exports = {
  process(src, path) {
    if (path.endsWith('.ts') || path.endsWith('.tsx')) {
      return tsc.transpile(
        src,
        {
          module: tsc.ModuleKind.CommonJS,
          jsx: tsc.JsxEmit.React,
        },
        path,
        []
      );
    }
    return src;
  },
};
```

This breaks my tests, because I need to have `experimentalDecorators: true` in there. I ejected the app and verified that this would indeed work.

Is there an easy way to use the `compilerOptions`-settings from the `tsconfig.json` in the project-root or overwrite the settings somehow?

### LINKED ISSUE #333: Consider relaxing lint rules
Hi folks!

We currently link to this project from React documentation. I haven’t tried it personally but I assumed it would follow the philosophy in CRA. In particular, we don’t use lint warnings but things that are inconsequential (code style) and only use them to warn people about actual bugs in their code. This was a major design decision after seeing beginners struggle with screens fully of linter errors about spacing and alphabetising props when *they’re just learning a library*!

However, I recently realized this project doesn’t actually subscribe to this philosophy, and has very strict lint rules:

https://twitter.com/ryanflorence/status/1002028375903354881

https://twitter.com/acemarke/status/1002029156492771328

I don’t want to debate usefulness of this, but I’m wondering how intentional it was. If it is intentional I think we’ll need to avoid recommending this setup for beginners, for the same reason we don’t recommend Airbnb config to them. But maybe it’s not that important and you can consider relaxing them to stay closer to CRA’s original vision?

Thanks for consideration.

### PR DESCRIPTION
**Pull request by nickmccurdy**
This is an attempt to fix #333 by replacing TSLint with CRA's default ESLint setup for a more beginner friendly setup that is consistent with what JS users of CRA are used to. May contain breaking changes. See my in depth rationale here: https://github.com/wmonk/create-react-app-typescript/issues/333#issuecomment-401642824

## Verification
- TSLint violations no longer appear (for example, removing `public` from `App.tsx`)
- ESLint warnings appear on TS files (for example, adding `eval('string')`)
- Linter passes on default template with `yarn start` and `yarn build`
- `yarn test` is unaffected
- ESLint behaves after ejecting

## Tasks
- Document migration from TSLint
- Consider using [eslint-plugin-typescript](https://github.com/nzakas/eslint-plugin-typescript) for TypeScript specific rules (currently JS rules run through a TS parser)
- Consider how to handle back compatibility (warning on tslint.json, major release, keeping TSLint and ESLint, etc.)
- Verify source maps

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Hi, thanks for doing this work. I'm trying to use it, and I'm running into an issue where I want to run the linter from the command line. Do you know how to go about that? If I run `eslint .` it complains about not having a config file. If I create an empty config file I get parsing errors on existing `.js` files.

Is there a recipe for doing this in CRA that I should be following?

Happy to dig into this, but I could use a few pointers.

**Comment by nickmccurdy** [comment]
Unlike CRA-TS, CRA does not generate an ESLint config and does not allow the internal config to be edited. The ESLint loader is built into commands like `npm start` and `npm run build` which you should run instead of `eslint .`, and it should behave exactly like CRA does (except with TS syntax support).

**Comment by paulmelnikow** [comment]
Gotcha. Thanks. So to make sure it's lint free in CI, I just run `npm run build`.

What's the rationale for not being able to override the config? Currently I'm running into an issue where there are lots and lots of false-positive `no-undef`'s on class properties. It's a similar issue to eslint/eslint#8720.

**Comment by nickmccurdy** [comment]
> What's the rationale for not being able to override the config?

This was CRA's decision, and I thought it would be simpler and less surprising to take the same decision. CRA's philosophy is that almost nothing is configurable, everything follows sane defaults.

> Currently I'm running into an issue where there are lots and lots of false-positive no-undef's on class properties.

Oops I didn't notice that issue. They say it was related to class properties, do you think the issue could be that we're using the typescript parser instead of eslint/babel?

> Is there a way to trigger autofix using the scripts?

No, but the default config is very minimal and has no style/syntax rules, so it probably wouldn't be useful anyway. ESLint can't really autofix most semantic rules, like defining used variables.

**Comment by paulmelnikow** [comment]
I ran into another false positive: `no-unused-vars` on an imported interface type.

> This was CRA's decision, and I thought it would be simpler and less surprising to take the same decision. CRA's philosophy is that almost nothing is configurable, everything follows sane defaults.

It makes sense, especially if the rules are extremely basic and always problems, as you say. If I want to lint additional stuff I can install and run my own copy of eslint. It's a bit frustrating in this circumstance, but that's only because of the issue we're discussing. 😁 

> … do you think the issue could be that we're using the typescript parser instead of eslint/babel?

Not sure, though I could give this a try.

It's also possible that we should just turn off this rules on `.ts` and `.tsx` files.

By the way, I do occasionally get the build to run and the app to display in the presence of lint errors. Maybe one time out of five this happens. That's why I was looking to trigger it separately in CI. It's unrelated to these changes – i.e. I've seen it happen both before and after this change.

**Comment by paulmelnikow** [comment]
Related discussions:

`no-unused-vars` issue: https://github.com/nzakas/eslint-plugin-typescript/issues/33#issuecomment-400063994 https://github.com/nzakas/eslint-plugin-typescript/issues/90 https://github.com/nzakas/eslint-plugin-typescript/issues/112

`no-undef` issue: nzakas/eslint-plugin-typescript/issues/110

**Comment by nickmccurdy** [comment]
You're right, there are issues with no-undef and no-unused-vars after all. I'm trying to fix these as it was not intentional and I don't want to force people to eject just to avoid ESLint parser bugs.

I think I'll just disable no-undef on TS files since TS errors on undefined variables anyway, but the TypeScript parser and plugin for ESLint don't seem to have an easy way to fix no-unused-vars. The default TS config has noUnusedLocals already which is half of the no-unused-vars, so what if we enabled noUnusedParameters to be consistent with eslint-config-react-app? Then we can disable the no-unused-vars rule, but we have to be careful with users changing allowJs and checkJs.

In other news ESLint seems to be making progress on Babel 7 based TypeScript support, but I don't think it's ready yet. The only other issue I've noticed so far is that ESLint seems to confuse the `<></>` React fragment shorthand syntax with strings, and I get a no-multiline-string-error.

**Comment by nickmccurdy** [comment]
Thanks, just skimmed those issues. I would much rather have the full type system support of noUnusedLocals and noUnusedParameters (which is much more stable) than have the ability to turn an error to a warning, especially since the current TSLint setup only shows one error at a time and we may need to make breaking changes anyway to switch people to TSLint.

I personally think disabling no-undef and no-unused-vars in TS is the way to go, but what should we do about checkJs? Should we enabled it by default and disable those rules in JS, or enable the rules in JS (which means that users enabling checkJs may see unused variable and undefined variable warnings twice, both in TS and ESLint)?

**Comment by paulmelnikow** [comment]
> Thanks, just skimmed those issues. I would much rather have the full type system support of noUnusedLocals and noUnusedParameters (which is much more stable) than have the ability to turn an error to a warning, especially since the current TSLint setup only shows one error at a time and we may need to make breaking changes anyway to switch people to TSLint.

Agreed. Turning off no-undef and no-unused-vars in TS sounds right. It might be possible to do that simply by turning off `typescript/no-undef` and `typescript/no-unused-vars`.

One thing, though: `-noUnusedParameters` seems to conflict with https://github.com/facebook/create-react-app/blob/8a34b7cc77099c7f591d64726a8106c02104f8f8/packages/eslint-config-react-app/index.js#L134 which has `args: 'none'`.

Does the TypeScript compiler report these errors on JS files? I'm pretty new to all of the TypeScript tooling, though I'd be surprised if it did.

**Comment by nickmccurdy** [comment]
Good catch, I thought CRA was using the default options for no-unused-vars. Unfortunately there's no exact alternative to after-unused in TS, but I think it would be fine to keep noUnusedParameters disabled by default since it's still configurable.

As far as I'm aware, noUnusedLocals and noUnusedParameters work on JS files if allowJs and checkJs are enabled. We currently only enable allowJs by default.

**Comment by paulmelnikow** [comment]
They're using `none`, not `after-unused`.

> As far as I'm aware, noUnusedLocals and noUnusedParameters work on JS files if allowJs and checkJs are enabled. We currently only enable allowJs by default.

Sounds like you think it'll currently be reported by eslint but not the compiler. I'll check.

**Comment by paulmelnikow** [comment]
Confirmed, I'm getting it from eslint but not the compiler.

A lint error in a JS file seems to be a reproducible example of this issue:

> By the way, I do occasionally get the build to run and the app to display in the presence of lint errors. Maybe one time out of five this happens. That's why I was looking to trigger it separately in CI. It's unrelated to these changes – i.e. I've seen it happen both before and after this change.

`yarn build` emits the warning but then runs to completion with a successful exit status. `yarn start` prints the warning in the console but the built site displays in the browser.

Think I should raise a new issue for that?

**Comment by nickmccurdy** [comment]
That's odd, the ESLint error is only showing up in the console? I see it in the console, command line, and browser, which I believe is the same as CRA.

**Comment by nickmccurdy** [comment]
Nevermind, this is consistent with CRA after all, it only shows errors in the browser overlay. The reason this didn't happen before is that the TS and TSLint loaders only reported errors, but most of eslint-config-react-app's rules are warnings.

**Comment by nickmccurdy** [comment]
I couldn't get eslint-plugin-typescript to work as expected, so for now I'm just disabling rules I know to be problematic in TS files. Thanks for your help.

My CRA-TS app is now free of ESLint errors and warnings after disabling the false positives, but I'd appreciate if you could test this new commit and see if your apps still have any incorrect warnings/errors. Besides discovering more problematic rules, we should consider forking eslint-config-react-app to reduce duplication, make it easier to configure editor ESLint plugins (they can't read Webpack configs), and allow usage outside of CRA-TS (CRA also supports their ESLint config for non-CRA users).

**Comment by paulmelnikow** [comment]
Will do.

> forking eslint-config-react-app to reduce duplication

Extending it might also be an option.

**Comment by nickmccurdy** [comment]
Good idea. In that case, should we edit the existing package in this repository or make a new directory in packages? I'm pretty new to Lerna and Yarn.

**Comment by paulmelnikow** [comment]
Since it's a new config rather than a fork of anything, I expect the cleanest way is to make a new directory in packages.

There must be some mechanism for publishing only certain packages, because some of the packages in this repo are not forked. I can't find it though. Maybe publish gets run manually from `packages/react-scripts`.

**Comment by paulmelnikow** [comment]
Can confirm b6acada57c064022a7f4813f491539c4960e584f is working great. 👍

**Comment by wmonk** [comment]
Hey all! Sorry i've not been involved in this, looks like some good work though. Just to double check this would allow us to have (almost) the identical rules to normal `react-scripts` right?

**Comment by nickmccurdy** [comment]
Yea, my goal is to fix #333 by using CRA's existing setup with some tweaks to support TypeScript parsing. Note that the ESLint config is not configurable by the user, this is intentional as it's very minimal and meant to detect obvious bugs, but if you're willing to publish a second package I can fork their ESLint config to make it easier to use in editors and React TS projects that aren't using CRA-TS.

As far as compatibility goes, this is a breaking change in the current state because it removes all TSLint integration and brings in an ESLint config that may introduce errors (thought I would expect it to be rare). Let me know if you're OK with this, or if you want some sort of back compatibility for the TSLint integration. Right now if a user decided to migrate to this from stable CRA-TS, they would need to install and run TSLint manually to continue using it, but that shouldn't be difficult.

**Comment by wmonk** [comment]
I think this looks good. Can you update your PR to fit the new repository structure? Thanks!

**Comment by nickmccurdy** [comment]
I can resolve the merge conflicts, but I was hoping that I could still publish the forked ESLint config as a separate package aso it can be used in editors conveniently (similar to https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#displaying-lint-output-in-the-editor). What would you prefer, a separate repository, making this a monorepo again, or an orphan branch?

**Comment by InExtremaRes** [comment]
I have some doubts. With this PR are we still able to use TSLint if we want to?

In our current project we are using CRA-TS and our linter rules are different from the default ones (some are more permissive other are stricter) and we would like to keep them that way.

It would be still possible to disable the built-in ESLint and replace it with TSLint without eject?

Thank you so much!

**Comment by nickmccurdy** [comment]
@wmonk I merged master and pushed a new commit to the same branch, but it's not appearing. Is this because of the fork link? Do I have to fork this repository again and send a new PR?

**Comment by InExtremaRes** [comment]
@nickmccurdy thank you for the quick answer. So, if we want to run tslint on `npm run build` we will have to adjust the npm scripts? What about running it on "live" in development server (`npm start`)?

**Comment by InExtremaRes** [comment]
@nickmccurdy Well, I understand the motivations behind this. I firmly believe that a tool like CRA, that pretends to implements a working environment the less painful and frictional as possible, should come with sane defaults that allows a "beginner developer" to enter smoothly, without a lot of unnecessary restrictions.

But IMHO a tool like that _should_ also allows to developers to change some configurations, specially if those are about consistency, codestyle or any similar rules a team wants to enforce, under their own responsibility of course. I think there is a difference between a ready-to-go tool and a restricted one.

I don't see anyone else complaining about this, so maybe this is the preferred approach. If that is the case, maintain compatibility for TSLint could be unnecessary. We wouldn't like to eject since CRA makes a very good job for us configuring webpack, jest, etc. Using app-rewired looks reasonable to me (as I said, own responsibility) but then a template or documentation about how to optionally enable TSLint is to be very thankfully.

**Comment by nickmccurdy** [comment]
Personally I'd rather follow CRA's approach to what is and isn't configurable as closely as possible (which is why this ESLint config isn't configurable), but I'm open to suggestions. To me it's not just about configurability, but preventing surprises for users coming from CRA. For example when I first started TSLint, I was confused about the different between tslint.json, tsconfig.json, tsconfig.prod.json, and tsconfig.dev.json. 

Maybe we should have a vote on if there should be back compatability for TSLint. I'd be happy to write basic 2docs either way.

**Comment by nickmccurdy** [comment]
Continued in #388.

**Pull request closed without merging**
