### PR TITLE
add typechecking to tslint

### PR DESCRIPTION
**Pull request by GabrielCastro**
This solves #126,
I ran eject on a project made these changes and no longer get the flash error from tslint

### CODE REVIEW

**Comment by gsteacy** [comment]
I'm not sure type checking should be enabled while this is still an issue: https://github.com/wbuchwalter/tslint-loader/issues/76. Even on small projects I noticed a performance hit of 250-300%.

**Comment by pelotom** [comment]
@gsteacy agreed, I've stopped using `tslint-loader` and switched to (`tslint-webpack-plugin`)[https://www.npmjs.com/package/tslint-webpack-plugin] because of this.

**Comment by stevenmusumeche** [comment]
@pelotom are you able to do that without ejecting though?

**Comment by pelotom** [comment]
@stevenmusumeche no.

**Comment by DorianGrey** [comment]
Suppose this is superseded by using `fork-ts-checker-webpack-plugin` introduced by https://github.com/wmonk/create-react-app-typescript/pull/165 - this already plugin already executes linter rules that require type checking by sharing the required `ts.Program` instance with the general type checker.

**Comment by wmonk** [comment]
As this issue hasn't been updated for a while, I am going to close it. If there are any updates feel free to re-open and comment. 👍

**Comment by DorianGrey** [comment]
FYI: [fork-ts-checker-webpack-plugin](https://github.com/Realytics/fork-ts-checker-webpack-plugin), which was added in 2.10, supports linting rules that require type checking by sharing `ts.Program` instances, so that feature should be available anyway.

**Comment by pelotom** [comment]
Yes, however be aware that `fork-ts-checker-webpack-plugin` has [a bug](https://github.com/Realytics/fork-ts-checker-webpack-plugin/issues/74) with the `no-unused-variable` rule which may or may not bite you. For my project it was intolerable; I had to disable the rule and use the `tsc` `—noUnusedLocals` flag instead.

**Comment by DorianGrey** [comment]
That's currently the case in the template - `noUnusedLocals` is used as a compiler option, `no-unused-variable` is not part of the linter config.

**Pull request closed without merging**
