### PR TITLE
CSS modules with Typings

### PR DESCRIPTION
**Pull request by tomaash**

### CODE REVIEW

**Comment by DorianGrey** [comment]
@tomaash , don't get me wrong - I appreciate the effort you've put into this.
But I think this is a bit too specialized to include it by default, especially since users that don't want to use it still have to live with the overhead it creates, at least without ejecting their project.
Furthermore, weakening the type checking strictness is something I'd not recommend or like, at least if it can be avoided.

However, I would be really useful to have this setup available in some kind of documentation for those interested in it.

**Comment by tomaash** [comment]
I agree, this cannot really be just merged. After some experimenting, I reverted my approach to not use `typings-for-css-modules-loader` as well. The overhead is just too much. I'll create another PR with less intrusive approach when I get it more polished.

**Comment by tomaash** [comment]
OK, so I just figured out that the best way to get CSS modules to any create-react-app setup is to use [react-app-rewired](https://github.com/timarney/react-app-rewired) Now my addons to react-scripts webpack are in a [plugin](https://github.com/tomaash/react-app-rewire-css-modules). Closing this PR.

**Comment by FDiskas** [comment]
@tomaash 
create-react-app css modules enabled by default.
Try creating css file
```css
:local {
.demo: { color: red; }
}
```
then just import it like
```js
import style from './my.css'
//...
<MyApp classname={style.demo} />
```

**Pull request closed without merging**
