### PR TITLE
Add support for setupTests.ts

### PR DESCRIPTION
**Pull request by ChrisJamesC**
For now it was not possible to use setupTests since it is a js file, so it is not handled by config/jest/typescriptTransform.js

### CODE REVIEW

**Comment by wmonk** [comment]
This looks good, thanks! I will look at getting it merged today

**Comment by ChrisJamesC** [comment]
@wmonk thanks for this fork, it's really nice to be able to work on a typescript app without leaving the comfort of create-react-app! 
Thanks for looking into it that fast.

**Comment by ChrisJamesC** [comment]
@wmonk Apparently the augmentation to the global scope in setupTests.ts causes issues (on `yarn start`). I'm looking into it, but if you have any idea please let me know.

**Comment by sebald** [comment]
@ChrisJamesC This might be because the `start` script will also parse all test files (when they are inside your `src` folder). If so, try excluding tests inside your `tsconfig` that helped me with a related problem :)

**Comment by wmonk** [comment]
@ChrisJamesC this is because tsc will parse all files in the `src` dir. You can do this:
```diff
diff --git a/tsconfig.json b/tsconfig.json
index 7127680..d4627d9 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -23,7 +23,8 @@
     "scripts",
     "acceptance-tests",
     "webpack",
-    "jest"
+    "jest",
+    "src/setupTests.ts"
   ],
   "types": [
     "typePatches"
```
to get this to work. I think it's ok to ignore this particular file as it's called out specifically in the README.

**Comment by ChrisJamesC** [comment]
@wmonk and @sebald thanks for the suggestion. I made the edit accordingly.

**Comment by wmonk** [comment]
@ChrisJamesC thanks for this, released! 🎉

**Pull request merged**
