### PR TITLE
Allow using different tsconfig files for dev and build

### PR DESCRIPTION
**Pull request by DorianGrey**
This PR adds the ability to use different configurations for dev and build mode for the `typescript` transpilation process.
Without further changes to the new `tsconfig.build.json`, the behavior will not change in any way, since it's just a no-op extension of the main `tsconfig.json`.

### CODE REVIEW

**Comment by wmonk** [comment]
Looks good! Do you think `build` is a clear enough name for this file?

**Comment by DorianGrey** [comment]
Have to admit that I'm still thinking about this -
- `build` closely refers to the task it is used by
- `prod` primarily refers to the config version it is referenced by

**Comment by DorianGrey** [comment]
OK, decided to go with `prod` instead of `build`. Makes somewhat more sense in this case.

**Comment by mbrowne** [comment]
I was copying this PR into my app which was ejected, and I noticed that [this line](https://github.com/DorianGrey/create-react-app-typescript/blob/a466da4ff6add04c64587a7285737b404b2e05f0/packages/react-scripts/config/webpack.config.prod.js#L134) of `webpack.config.prod.js` was left unmodified:

`new TsconfigPathsPlugin({ configFile: paths.appTsConfig })`

I think maybe that should be changed to `paths.appTsConfig` also?

**Comment by DorianGrey** [comment]
Yes, there is already a (pending) PR for this change: https://github.com/wmonk/create-react-app-typescript/pull/323/files
It somehow got lost when creating and merging this PR.

**Pull request merged**
