### PR TITLE
Update tslint to 5.2.0 - fixes #40

### LINKED ISSUE #40: Update TSLint to v5?

### PR DESCRIPTION
**Pull request by mindjuice**
Also updated other TS dependencies.

Tested by creating a project and using `npm link` to connect to my git repo, then ran the following commands from `react-scripts-ts`:
```
rm -rf node_modules
yarn install
yarn build       # Verified that there were no errors during the build
serve -s build   # Verified that app loaded and ran with no errors
yarn start       # Verified that app loaded and ran with no errors
```

Also verified that linting is working correctly by making some rule changes and code changes and seeing the lint errors appear while `yarn start` was running.

I'm wondering if you have a better way of testing/running changes to the app than this.

### CODE REVIEW

**Comment by wmonk** [comment]
Thanks for this! First thing I want to do is get create react app 1 in. Then we will get this merged!

**Comment by wmonk** [comment]
hey @mindjuice, thanks for this! Have merged in cra@1.0.4 now, so please can you rebase your PR against that!

The tests are all working fine now, so please run yarn run e2e at the root of the repo before you push.

**Comment by mindjuice** [comment]
Thanks.  Will do tonight.

**Comment by mindjuice** [comment]
Hmmm...I ran `yarn run e2e` on the repo and get an error (see below).  I reverted my changes though and ran it again and get the same error, so not sure what is causing the error, but I don't think it's my changes.

Not sure if you're able to try it, but if not I'll look into it some more tomorrow night.

```
 RUNS  src/App.test.tsx
2017-05-23 22:38 node[73466] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-05-23 22:38 node[73466] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2 RUNS  src/App.test.tsx
2017-05-23 22:38 node[73466] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1023:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1283:11)
npm ERR! Test failed.  See above for more details.
++ set +x
e2e-simple.sh: ERROR! An error was encountered executing line 303.
Cleaning up.
Exiting with error.

npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/kencr2000/.nvm/versions/node/v7.5.0/bin/node" "/Users/kencr2000/.nvm/versions/node/v7.5.0/bin/npm" "run" "e2e"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! @ e2e: `tasks/e2e-simple.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ e2e script 'tasks/e2e-simple.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tasks/e2e-simple.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kencr2000/dev/github/create-react-app-typescript/npm-debug.log
```

**Comment by wmonk** [comment]
Think as it's passed fine in travis I'm happy!

**Pull request merged**
