### PR TITLE
Upgrade typescript to 2.2.2

### PR DESCRIPTION
**Pull request by jeremistadler**

### CODE REVIEW

**Comment by jeremistadler** [comment]
Published here https://www.npmjs.com/package/@jeremi/react-scripts-ts

**Comment by TobiasBales** [comment]
Can this be merged or is there anything from stopping it going live?

**Comment by jeremistadler** [comment]
Im using it live without any problems

**Comment by wmonk** [comment]
Released in 1.3.0 🎉

**Pull request merged**
