### PR TITLE
Add support for fork-ts-checker-webpack-plugin

### PR DESCRIPTION
**Pull request by johnnyreilly**
Like #161 but hopefully right first time!

### CODE REVIEW

**Comment by DorianGrey** [comment]
Just one thing:
You have to add the path resolution for `tslint.json` additionally somewhere around here:
https://github.com/johnnyreilly/create-react-app-typescript/blob/99a55a9272cbaad205b8d3cdba84ded09b268ee0/packages/react-scripts/config/paths.js#L63 (equiv. to the resolution of the `tsconfig.json`)

The part where you have added the resolution will work only for non-ejected projects, since it will be removed on ejection (see the markers: https://github.com/johnnyreilly/create-react-app-typescript/blob/99a55a9272cbaad205b8d3cdba84ded09b268ee0/packages/react-scripts/config/paths.js#L68 resp. https://github.com/johnnyreilly/create-react-app-typescript/blob/99a55a9272cbaad205b8d3cdba84ded09b268ee0/packages/react-scripts/config/paths.js#L126).

**Comment by johnnyreilly** [comment]
Thanks @DorianGrey - made adjustments accordingly

**Comment by DorianGrey** [comment]
@wmonk :
This PR looks good technically.
Merging this would supersede https://github.com/wmonk/create-react-app-typescript/pull/140, since the forked process already executes tslint with support for rules that require type-checking.
However, it would also conflict with the PR that request to replace `ts-loader` with `awesome-typescript-loader` (https://github.com/wmonk/create-react-app-typescript/pull/74).

From my personal experience, I'd recommend to pick this version instead of atl. In every project I've worked with this setup yet, it always resulted in a better performance than using atl, and it also performs linting with type checks, which would otherwise be extremely expensive when used via `tslint-loader`.

**Comment by johnnyreilly** [comment]
@DorianGrey  / @wmonk - I've just fixed the merge conflict.

**Comment by wmonk** [comment]
What should the versioning look like for this do you think? Is this likely to cause issue for existing users?

**Comment by johnnyreilly** [comment]
Sorry, could you clarify what you mean please @wmonk? I don't think this should cause an issue for existing users - should be like for like replacement. Not breaking changes.

**Comment by wmonk** [comment]
Ok cool, that's all I wanted to check.

**Comment by caghand** [comment]
Hi Johnny and Will,

Thanks for working on this.  However, I've noticed that this PR did not get merged properly to master.

In particular, the tslint-loader rule has not been removed from webpack.config.prod.js, as intended.

This causes "type information" warnings (like in #126) to be emitted during `npm run build` (or `yarn build`), which uses webpack.config.prod.js.

Could you take a look?  Thanks!

-Caghan

**Comment by caghand** [comment]
Thanks for the quick fix and the publish!  I was able to confirm that it works perfectly now.  The warnings are gone for good.
By the way, the 2.13.0 release needs upgrade/migration instructions: The user must manually add "typescript" as a dev dependency to existing projects.  Otherwise, there will be build errors.

-Caghan

**Comment by vire** [comment]
`tslint: paths.appTsLint,` in

```
new ForkTsCheckerWebpackPlugin({
      async: false,
      watch: paths.appSrc,
      tsconfig: paths.appTsConfig,
      tslint: paths.appTsLint,
    }),
```
is causing re-build failure, it says it can't find some `node_modules` module 

I think this issue is related to TSLint

**Comment by mukeshkamboj** [comment]
@vire did you find the solution of cannot fine module problem?

**Comment by mukeshkamboj** [comment]
@vire Please ignore. setting the no-unused-variable to false in tslint solved the issue.

**Pull request merged**
