### PR TITLE
✅  Upstream sync (Nov 5 2017)

### LINKED ISSUE #182: babel & raf missing after eject. Deps out of date
In comparing the typescript `create-react-app` ejected `package.json` to upstream, I noticed some differences.

- Is `babel` suppose to be missing? 
- Is `raf` removed intentionally?
- Most of the dependency versions are out of date.
- `registerServiceWorker.js` is missing

I'm guessing these issues will be resolved after rebasing on Facebook's latest changes.

<details><summary>Facebook create-react-app</summary>

```
"dependencies": {
    "autoprefixer": "7.1.6",
    "babel-core": "6.26.0",
    "babel-eslint": "7.2.3",
    "babel-jest": "20.0.3",
    "babel-loader": "7.1.2",
    "babel-preset-react-app": "^3.1.0",
    "babel-runtime": "6.26.0",
    "case-sensitive-paths-webpack-plugin": "2.1.1",
    "chalk": "1.1.3",
    "css-loader": "0.28.7",
    "dotenv": "4.0.0",
    "eslint": "4.10.0",
    "eslint-config-react-app": "^2.0.1",
    "eslint-loader": "1.9.0",
    "eslint-plugin-flowtype": "2.39.1",
    "eslint-plugin-import": "2.8.0",
    "eslint-plugin-jsx-a11y": "5.1.1",
    "eslint-plugin-react": "7.4.0",
    "extract-text-webpack-plugin": "3.0.2",
    "file-loader": "1.1.5",
    "fs-extra": "3.0.1",
    "html-webpack-plugin": "2.29.0",
    "jest": "20.0.4",
    "object-assign": "4.1.1",
    "postcss-flexbugs-fixes": "3.2.0",
    "postcss-loader": "2.0.8",
    "promise": "8.0.1",
    "raf": "3.4.0",
    "react": "^16.0.0",
    "react-dev-utils": "^4.2.1",
    "react-dom": "^16.0.0",
    "style-loader": "0.19.0",
    "sw-precache-webpack-plugin": "0.11.4",
    "url-loader": "0.6.2",
    "webpack": "3.8.1",
    "webpack-dev-server": "2.9.4",
    "webpack-manifest-plugin": "1.3.2",
    "whatwg-fetch": "2.0.3"
  },
```
</details>

<details><summary>wmonk create-react-app</summary>

```
"dependencies": {
    "autoprefixer": "7.1.2",
    "case-sensitive-paths-webpack-plugin": "2.1.1",
    "chalk": "1.1.3",
    "css-loader": "0.28.4",
    "dotenv": "4.0.0",
    "extract-text-webpack-plugin": "3.0.0",
    "file-loader": "0.11.2",
    "fs-extra": "3.0.1",
    "html-webpack-plugin": "2.29.0",
    "jest": "20.0.4",
    "object-assign": "4.1.1",
    "postcss-flexbugs-fixes": "3.2.0",
    "postcss-loader": "2.0.6",
    "promise": "8.0.1",
    "react": "^16.0.0",
    "react-dev-utils": "^4.0.1",
    "react-dom": "^16.0.0",
    "source-map-loader": "^0.2.1",
    "style-loader": "0.18.2",
    "sw-precache-webpack-plugin": "0.11.4",
    "ts-jest": "^20.0.7",
    "ts-loader": "^2.3.7",
    "tslint": "^5.7.0",
    "tslint-loader": "^3.5.3",
    "tslint-react": "^3.2.0",
    "typescript": "~2.5.3",
    "url-loader": "0.5.9",
    "webpack": "3.5.1",
    "webpack-dev-server": "2.7.1",
    "webpack-manifest-plugin": "1.2.1",
    "whatwg-fetch": "2.0.3"
  },
```
</details>

### PR DESCRIPTION
**Pull request by bootstraponline**
I rebased the TypeScript changes on upstream `create-react-app`. Travis CI is passing. ✅ 

It'd be great to have this merged to keep current with React changes. 

Fixes #182

----

There are two commits:

1. `Pull latest from facebookincubator/create-react-app` 
    - rsync from upstream repo
1. `Rebase TypeScript changes` 
    - TypeScript specific modifications

### CODE REVIEW

**Comment by smacpherson64** [comment]
@bootstraponline This would also affect other issues as well:

May affect and help with: #186 as dependencies of `react-scripts-ts` react dependency becomes 16 instead of 15

Would fix: #173 

Hope this helps!

**Comment by wmonk** [comment]
Many thanks!

**Comment by wmonk** [comment]
Released in 2.9.0, thanks again!

**Comment by bootstraponline** [comment]
Thank you!! create-react-app-typescript is awesome.

**Comment by edzis** [comment]
@wmonk Is 2.9.0 released or not? I see 2.8.0 on https://www.npmjs.com/package/react-scripts-ts and in my `package.json` after running `create-react-app my-app --scripts-version=react-scripts-ts`.

**Comment by DorianGrey** [comment]
@edzis 2.9.0 was released, but got unpublished due to several issues that have to be fixed upstream (i.e. in CRA) before it can be considered 'stable' again. Next merge is planned for the next CRA release.

**Pull request merged**
