### PR TITLE
Absolute paths using `REACT_APP_NODE_PATH` instead of `NODE_PATH`

### LINKED ISSUE #122: jest tests failing with "Unexpected token export" when using absolute imports
### Description

The apparent recommended solution for achieving absolute imports, most recently referenced in #119, is to add a `node_modules` folder or symlink in `src`. Because NODE_ENV doesn't work in Typescript, I believe this is the only way to do absolute imports in create-react-app-typescript.

However, I am seeing jest tests choke when using such imports with `SyntaxError: Unexpected token export` errors.

Weirdly this may be somehow related to using enums? See the reproducible demo below.

### Expected behavior

Expect jest tests to work.

### Actual behavior

Jest fails with:

```
    SyntaxError: Unexpected token export

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
      at Object.<anonymous> (src/App.tsx:15:17)
      at Object.<anonymous> (src/App.test.tsx:5:13)
```

### Environment

react-scripts-ts@2.5.0
node 8.2.1
npm 5.3.0

### Reproducible Demo

I created a reproducible demo here:

https://github.com/eonwhite/absolute-imports

To reproduce the issue, git clone and npm install, then:
- Try `npm start` and note that the "app" works.
- Try `npm test` and note that tests fail with `SyntaxError: Unexpected token export`

Note that you can get jest to run and the tests to pass by:
- changing the absolute import on line 5 of App.tsx to a relative import: `import { MyModel, Type } from './common/model/MyModel';`
- removing the `Type` enum in `src/common/model/MyModel.ts` (and the references to the enum in App.tsx)

Obviously though I'm seeking a solution that lets me use absolute imports and enums in my code.

### PR DESCRIPTION
**Pull request by smacpherson64**
Aimed to fix #122 

Creating concept to utilize `REACT_APP_` variables in `.env` files to solve the issue of Absolute paths.

### CODE REVIEW

**Comment by wmonk** [comment]
@eonwhite @doriangrey could you have a look over this?

**Comment by DorianGrey** [comment]
I'm not sure about the advantage of renaming `NODE_PATH` to `REACT_APP_NODE_PATH`, though. `NODE_PATH` is handled properly using `webpack` and `jest`, and `tsc` simply ignores it, so it should not conflict with anything else.
In general, the idea of using `baseUrl` should work, at least for a single folder to look non-relative linked modules up from. It will require a bit of documentation, though - while `.env` files and thus `NODE_PATH` might include multiple paths, `baseUrl` will only be able to deal with a single one automatically, additional mappings require the `paths` definition. It might be useful to add an additional warning or possibly an error if multiple paths are defined using the `.env` strategy. Alternatively, it should be possible to provide a check if the `NODE_PATH` entries have matching counterparts defined in the `tsconfig.json`, and only throw an error in that case.

**Comment by smacpherson64** [comment]
Hey @DorianGrey @wmonk Thank you for responding!

I apologize for the background, just want to make sure I am on point or I am off. (If I am off, I would greatly appreciate any response, Thanks again for your time!)

About the switching from `NODE_PATH` to `REACT_APP_NODE_PATH`, I am using `react-scripts-ts` version 2.8.0 on Windows 10 and am unable to use `NODE_PATH` as it returns undefined in the following situations:

> `.env` files
> NODE_PATH=src

> In `package.json` scripts:
>`set NODE_PATH=src&&...`

I tried various variants, but `NODE_PATH` was always coming back undefined. All other variables were coming through properly.

When setting the `baseUrl` to `src` in tsconfig.json, my editor would find the module however the app could not compile:
```
Module not found: Can't resolve 'src/components/Component' in 'c:\projects\testing\my-app\src\domains\marketing\screens\Styleguide\components\StyleguideSectionColors' 
```

My editor VSCode  would find the module because `baseUrl` was set in tsconfig.json.

**Comment by smacpherson64** [comment]
Again, apologies, going to remove all traces of responses in #122 to reduce confusion. I ran through tests again, and `NODE_PATH` is working as desired.

**Actions taken:**
* Creating a `.env` file in project root with:
```NODE_PATH=src```

* Adding baseUrl option in `tsconfig.json`
```"baseUrl": "src"```

* Setup Absolute Import
```import { Component } from components/Component```

It is thus unnecessary to rename `NODE_PATH` for my setup (Windows 10, Node 8.7.0, react-scripts-ts 2.8.0). Note: I didn't need to set up `paths` in tsconfig.json yet, as I only used one path. I have not tested setting up paths.

Again, Apologies, thanks for your time!

**Comment by smacpherson64** [comment]
@DorianGrey here is a concept that may work in `env.js` after the NODE_PATH declaration (line 58)

 ```js
  if (!!process.env.NODE_PATH) {
    const tsconfig = JSON.parse(fs.readFileSync(paths.appTsConfig, 'utf8'));
    const hasMultiplePaths = process.env.NODE_PATH.indexOf(path.delimiter) !== -1;
    const hasBaseUrl = typeof tsconfig.compilerOptions.baseUrl !== 'undefined';
    const hasPaths = typeof tsconfig.compilerOptions.paths !== 'undefined';
  
    if (hasMultiplePaths && !(hasBaseUrl && hasPaths)) {
      throw new Error(
        `Setting multiple paths using the NODE_PATH env variable requires adding baseUrl and paths to compilerOptions in tsconfig.json. For more information on how to setup paths in tsconfig.json visit: https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping
        
        `
      );
    }
  
    if (!hasBaseUrl) {
      throw new Error(
        `Setting a path using the NODE_PATH env variable requires adding baseUrl to compilerOptions in tsconfig.json. For more information on how to setup baseUrl visit: https://www.typescriptlang.org/docs/handbook/module-resolution.html#base-url
        
        `
      );
    }
  }
```

**Comment by DorianGrey** [comment]
Just a short hint for
> In package.json scripts:
> set NODE_PATH=src&&...

That does not work really well in most terminals on windows when `npm` or `yarn` are involved. In cases where this kind of setting environment variables is required, I've always used [cross-env]( https://github.com/kentcdodds/cross-env) to get it working in a cross-platform way.
```cross-env NODE_PATH=src <your command>```
Using the native `set` on windows under these circumstances always behaves a bit ... odd. Sometimes more than just a bit. So this is a general problem that CRA suffers from as well, unless used properly.

Regarding the checks: The seconds check looks good. However, there is a caveat on the first check:
```
if (hasMultiplePaths && !(hasBaseUrl && hasPaths)) {
     throw new Error(
       `Setting multiple paths using the NODE_PATH env variable requires adding baseUrl and paths to compilerOptions in tsconfig.json. For more information on how to setup paths in tsconfig.json visit: https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping
       `
     );
   }
```
This one isn't precise enough - it would only check for an amount, not for matching paths. 
E.g. using a `"baseUrl": "src"` and 
```
"paths": {
    "example/*": "common/whatever/*"
}
```
it should be ensured that all paths included by `NODE_PATH` should be listed as keys here (but beware of skipping the wildcard), in this case `example`. If `NODE_PATH` would include `example2` instead of `example`, the check should *not* pass, but it would in the current state.
Setting up a check like this is not a trivial task, though - however, I'd say it's worth the time, since failing on proper configuration is too easy here without guidance.

**Comment by smacpherson64** [comment]
Hey @DorianGrey, I am going to put examples below to see if I am understanding these correctly. If you have time please let me know your thoughts!

## Assumptions
> - When dealing with paths, all are based upon baseUrl (`baseUrl` + `paths`)
> - Path Matches can have an array or string of values for their locations to validate against.

## Examples
Assuming the following import on the examples:
```js
import 'src/common/components/Test'
```



### Example 1 - Match anything with two search paths (glob & generated/glob)

**tsconfig.json**
```
...
"baseUrl": ".",
"paths": {
  "*": [
    "*",
    "generated/*"
  ]
},
```

**Result:**
Matches and looks for the module in the following location(s):
`./src/common/components/Test`
`./generated/src/common/components/Test`




### Example 2 - Match `src` folder
```js
import 'src/common/components/Test'
```

**tsconfig.json**
```
...
"baseUrl": ".",
"paths": {
  "src/*": "src/*",
},
```

**Result:**
Matches and looks for the module in the following location(s):
`./src/common/components/Test`





### Example 3 - Match `common` folder with `src` as baseUrl

**tsconfig.json**
```
...
"baseUrl": "src",
"paths": {
  "common/*": "common/*",
},
```

**Result:**
Matches and looks for the module:
`./src/common/components/Test`


### Example 4 - Multiple matches with baseUrl as `src`

**tsconfig.json**
```
...
"baseUrl": "src",
"paths": {
  "another/*": "another/*"
  "common/*": "common/*",
},
```

**Result:**
The first match fails, The second match succeeds and looks for the module in the following location(s):
`./src/common/components/Test`

**Comment by DorianGrey** [comment]
Examples 2, 3 and 4 should be correct, from what I can see.
If I got that in mind correctly, the first example won't work, i.e. you'd get a compiler error here - path mappings have to include paths that are not only wildcards.

**Comment by smacpherson64** [comment]
Hey @DorianGrey,

Sorry for taking so long to respond, Example 1 was from the configs on the typescript site above wasn't sure about that.

Here is round two, this would conceptually be placed around line 47 on `react-scripts-ts/config/env.js`. before the setting of `process.env.NODE_PATH =(process.env.NODE_PATH || {})`

```JS
/**
 * Determine if tsconfig.json and NODE_ENV contain the same configuration with paths.
 * 
 * @param {*} tsconfig compilerOptions
 * @param {*} The process.env.NODE_ENV variable
 */
function validatePathsMatchBetweenConfigs(compilerOptions, nodePaths) {
  const tsPaths = compilerOptions.paths;

  const mismatchedPaths = nodePaths
    .split(path.delimiter)
    .reduce(
      (unmatchedPaths, nodePath) => unmatchedPaths.filter(tsPath => tsPath !== nodePath),
      Object.keys(tsPaths).map(key => `${compilerOptions.baseUrl}/${tsPaths[key]}`)
    );

  return mismatchedPaths.length === 0;
}

if (!!process.env.NODE_PATH) {
  const tsconfig = JSON.parse(fs.readFileSync(paths.appTsConfig, 'utf8'));
  const options = tsconfig.compilerOptions;
  const nodePath = process.env.NODE_PATH;
  const hasMultiplePaths = nodePath.indexOf(path.delimiter) !== -1;
  const hasBaseUrl = typeof options.baseUrl !== 'undefined';
  const hasPaths = typeof options.paths !== 'undefined';

  if (hasMultiplePaths) {
    if (!(hasBaseUrl && hasPaths)) {
      throw new Error(
        `Setting multiple paths using the NODE_PATH env variable requires adding baseUrl and paths to compilerOptions in tsconfig.json. For more information on how to setup paths in tsconfig.json visit: https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping
          
        `
      );
    }

    const pathsAreInSync = validatePathsMatchBetweenConfigs(options, nodePath);

    if (!pathsAreInSync) {
      throw new Error(
        `A mismatch exists between NODE_PATH env variable and paths set in the compilerOptions in tsconfig.json. For more information on how to setup paths and baseUrl visit: https://www.typescriptlang.org/docs/handbook/module-resolution.html#base-url
            
        `
      );
    }
  }

  if (!hasBaseUrl) {
    throw new Error(
      `Setting a path using the NODE_PATH env variable requires adding baseUrl to compilerOptions in tsconfig.json. For more information on how to setup baseUrl visit: https://www.typescriptlang.org/docs/handbook/module-resolution.html#base-url
         
      `
    );
  }
}
```

**Comment by DorianGrey** [comment]
There are several caveats with this approach.

1. Reading the typescript compiler options is a bit more complicated than just picking up a json file, at least in the general case. This is caused by the `extends` clause. I've once implemented this for the `ts-jest` project [here](https://github.com/kulshekhar/ts-jest/blob/0643b0341e2b28e1ec0b2c830e5dae1d5862d8f2/src/utils.ts#L78).
2. The `if (!(hasBaseUrl && hasPaths)` condition has to be used even if there is just one path in `nodePath`, not only in case of multiple paths.
3. The path comparison has to be performed for just a single path provided by NODE_ENV as well.
4. The path comparison has to ignore potentially existing glob wildcards and trailing slashes.

Never mentioned this would by easy ;)
Considering the amount of effort this comparison takes and the potential misbehaviors (i.e. failed or inaccurate checks) that may occur, I'd recommend to not break with an error in every potential case, just in the basic ones like `if there is at least a single path in NODE_ENV, there has to be a baseUrl in the tsconfig`.

**Comment by smacpherson64** [comment]
Thank you again for your time @DorianGrey!

Agreed on the full matching it seems that any match checking would end up being brittle in nature. (2, 3, and 4).

1. For basic path matching we would need to handle the extends clause like you have done for tslint. 
I had a fun looking through [your implementation above](https://github.com/kulshekhar/ts-jest/blob/0643b0341e2b28e1ec0b2c830e5dae1d5862d8f2/src/utils.ts#L78),  https://github.com/Microsoft/TypeScript/issues/5276 and https://github.com/Microsoft/TypeScript/blob/v2.5.3/src/compiler/commandLineParser.ts.

Below in the gist I reworked the concept (moving towards external file) using the direct port of what you used for tslint. I added a concept in, if the system does throw an error we could put an example (clearly marked as an example partial) so that users could get a quick idea of a possible way to use `baseUrl` and `paths`:

**Multiple Paths**
> Error: Setting multiple paths using the NODE_PATH env variable requires adding baseUrl and paths to compilerOptions in tsconfig.json. For more information on how to setup paths in tsconfig.json visit: https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping
>
> Below is a partial tsconfig.json example displaying baseUrl and paths usage:
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "src": "src",
      "test": "test"
    }
  }
}
```

**Single Path**
>Error: Setting a path using the NODE_PATH env variable requires adding baseUrl to compilerOptions in tsconfig.json. For more information on how to setup baseUrl visit: https://www.typescriptlang.org/docs/handbook/module-resolution.html#base-url
>
> Below is a partial tsconfig.json example displaying baseUrl usage:
```
{
  "compilerOptions": {
    "baseUrl": "src"
  }
}
```

Again appreciate your thoughts and time!

https://gist.github.com/smacpherson64/425d8003d9033d83f85e445b8c5fbb61

**Comment by DorianGrey** [comment]
That looks good, aside from some (minor) code issues:
- `getStartDir` seems to be unused ... don't think we'll need this ;) And even if it is required to pick up some paths, the `paths` module should be used for this, since it also handles potentially different resolution with or without ejection.
- [This line](https://gist.github.com/smacpherson64/425d8003d9033d83f85e445b8c5fbb61#file-pathmatcher-js-L90) seems curious - the variable you're referring to (`tsconfig`) does not exist.
- The displayed examples are a bit trivial - I'd prefer something more realistic, like:
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "shared/*": "src/shared/*",
      "someFeature/*": "src/someFeature/*"
    }
  }
}
```

A more detailed comparison of the paths would be favorable, but I'm afraid there is quite a huge potential for false positives during this evaluation. Suppose it's better to leave it cut off as it is in your current implementation. Might add some improvements here in case we find a robust way to implement such checks.

Thinking about this a little more, it comes to my mind that `process.env.NODE_PATH` may potentially contain arbitrary paths - they do not necessarily have to be linked to the project. We should only complain about paths that affect the current project. Including files outside of the current project is already blocked by default (by the `ModuleScopePlugin`).

Something like:
```javascript
const paths = require('./paths');
// ...
const currentPath = paths.resolveApp();
const nodePaths = nodePathEnv
  .split(path.delimiter)
  .filter(p => p.indexOf(currentPath) >= 0)
;
if (nodePaths.length > 0) {
  // The rest of the checks
}
```

**Pull request closed without merging**
