### PR TITLE
Makes getting started a one-liner

### PR DESCRIPTION
**Pull request by codereviewvideos**
https://blog.npmjs.org/post/162869356040/introducing-npx-an-npm-package-runner :)

Feel free to change the wording, or completely disregard. I won't be offended :)

Thank you for making and sharing this, I really appreciate it.

### CODE REVIEW

**Comment by elektronik2k5** [comment]
This is a great suggestion! I'd only add the fact that `npx` assumes a modern version of npm: >=5.2.0, which comes bundled with node >= 8.
Just to cover the case of someone trying to use `npx` in an ancient environment.

**Comment by DorianGrey** [comment]
CRA has a similar suggestion here: https://github.com/facebook/create-react-app#quick-overview
These should be roughly equivalent.

**Comment by TomasDuda** [comment]
yarn instructions are also missing - one-liner is:

```bash
yarn create react-app my-app --scripts-version=react-scripts-ts
```

**Comment by nickmccurdy** [comment]
It's even shorter in npm now: `npm create react-app my-app --scripts-version=react-scripts-ts`

**Pull request merged**
